<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Plugin strings are defined here.
 *
 * @package     local_assign_ai
 * @category    string
 * @copyright   2025 Datacurso
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['actions'] = 'Actions';
$string['aistatus'] = 'AI Status';
$string['email'] = 'Email';
$string['feedbackcomments'] = 'Comments';
$string['fullname'] = 'Full name';
$string['grade'] = 'Grade';
$string['lastmodified'] = 'Last modified';
$string['manytasksreviewed'] = '{$a} tasks reviewed';
$string['modaltitle'] = 'AI Feedback';
$string['norecords'] = 'No records found';
$string['nostatus'] = 'No feedback';
$string['notasksfound'] = 'No task to review';
$string['onetaskreviewed'] = '1 task reviewed';
$string['pluginname'] = 'Assignment AI';
$string['privacy:metadata:local_assign_ai_pending'] = 'Stores pending AI-generated assignment feedback awaiting approval.';
$string['privacy:metadata:local_assign_ai_pending:approval_token'] = 'A unique token used for approval tracking.';
$string['privacy:metadata:local_assign_ai_pending:assignmentid'] = 'The assignment this AI feedback relates to.';
$string['privacy:metadata:local_assign_ai_pending:courseid'] = 'The course associated with this feedback.';
$string['privacy:metadata:local_assign_ai_pending:grade'] = 'The proposed grade generated by the AI.';
$string['privacy:metadata:local_assign_ai_pending:message'] = 'The feedback message generated by the AI.';
$string['privacy:metadata:local_assign_ai_pending:rubric_response'] = 'The AI-generated rubric feedback.';
$string['privacy:metadata:local_assign_ai_pending:status'] = 'The approval status of the feedback.';
$string['privacy:metadata:local_assign_ai_pending:title'] = 'The title of the generated feedback.';
$string['privacy:metadata:local_assign_ai_pending:userid'] = 'The user for whom the AI feedback was generated.';
$string['qualify'] = 'Grade';
$string['review'] = 'Review';
$string['reviewall'] = 'Review all';
$string['reviewwithai'] = 'Review with AI';
$string['save'] = 'Save';
$string['saveapprove'] = 'Save and Approve';
$string['status'] = 'Status';
$string['statusapprove'] = 'Approved';
$string['statuspending'] = 'Pending';
$string['submission_new'] = 'New';
$string['submission_none'] = 'No submission';
$string['submission_submitted'] = 'Submitted';
$string['submittedfiles'] = 'Submitted files';
$string['viewdetails'] = 'View details';
